# Generated by Django 5.1.2 on 2025-06-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realblog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('from_club', models.CharField(max_length=100)),
                ('to_club', models.CharField(max_length=100)),
                ('transfer_date', models.DateField()),
                ('transfer_fee', models.CharField(max_length=100)),
            ],
        ),
    ]
