# Generated by Django 5.1.2 on 2025-06-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realblog', '0002_transfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.PositiveIntegerField()),
                ('position', models.CharField(choices=[('GK', 'Portar'), ('DF', 'Fundaș'), ('MF', 'Mijlocaș'), ('FW', 'Atacant')], max_length=2)),
                ('photo', models.ImageField(upload_to='players/')),
                ('is_starting', models.BooleanField(default=False)),
                ('x_pos', models.FloatField(blank=True, null=True)),
                ('y_pos', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
