# Generated by Django 5.1.2 on 2025-06-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realblog', '0003_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rumor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='rumors/')),
                ('position', models.CharField(max_length=50)),
                ('current_club', models.CharField(max_length=100)),
                ('chance', models.PositiveIntegerField(default=50)),
            ],
        ),
    ]
