# Generated by Django 5.1.2 on 2025-06-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realblog', '0004_rumor'),
    ]

    operations = [
        migrations.CreateModel(
            name='NextMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=100)),
                ('data', models.DateField()),
            ],
        ),
    ]
