# Generated by Django 5.1.2 on 2025-06-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realblog', '0006_match_delete_nextmatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Legends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_legend', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='transfer',
            name='image_transfer',
            field=models.ImageField(default=True, upload_to=''),
        ),
    ]
