# Generated by Django 5.2.3 on 2025-06-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realblog', '0008_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfer',
            old_name='transfer_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='transfer',
            old_name='from_club',
            new_name='from_team',
        ),
        migrations.RenameField(
            model_name='transfer',
            old_name='to_club',
            new_name='to_team',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='image_transfer',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='transfer_fee',
        ),
        migrations.AddField(
            model_name='transfer',
            name='fee',
            field=models.CharField(default='Free', max_length=50),
        ),
    ]
