# Generated by Django 5.2.3 on 2025-06-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realblog', '0010_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='description',
            field=models.TextField(default='description'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='players/'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='fee',
            field=models.CharField(max_length=50),
        ),
    ]
