# Generated by Django 5.2.3 on 2025-06-23 16:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realblog', '0011_transfer_description_transfer_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rumor',
            old_name='current_club',
            new_name='from_team',
        ),
        migrations.RenameField(
            model_name='rumor',
            old_name='name',
            new_name='player_name',
        ),
        migrations.RemoveField(
            model_name='rumor',
            name='chance',
        ),
        migrations.RemoveField(
            model_name='rumor',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='rumor',
            name='position',
        ),
        migrations.AddField(
            model_name='rumor',
            name='credibility',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='rumor',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='rumor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='rumors/'),
        ),
        migrations.AddField(
            model_name='rumor',
            name='source',
            field=models.CharField(default='necunoscut', max_length=100),
        ),
    ]
